# ios/Podfile

# Use the React Native CocoaPods helper from node_modules
require Pod::Executable.execute_command(
  'node', [
    '-p',
    'require.resolve("react-native/scripts/react_native_pods.rb", { paths: [process.argv[1]] })',
    __dir__
  ]
).strip

platform :ios, '16.0'

prepare_react_native_project!

target 'tempRepair' do
  # Pull in all the pods defined in react-native-linkable modules
  config = use_native_modules!

  use_react_native!(
    # Path to your RN project
    :path => config[:reactNativePath]
  )

  # Make sure vector icons are included
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'tempRepairTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Standard RN post-install
    react_native_post_install(installer, config[:reactNativePath])
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
        config.build_settings['OTHER_CFLAGS']   << '-Wno-non-modular-include-in-framework-module'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)']
        config.build_settings['OTHER_CPLUSPLUSFLAGS']   << '-Wno-non-modular-include-in-framework-module'
      end
    end
  end
end