require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.0'
project 'VocabMaster.xcodeproj'

target 'VocabMaster' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  target 'VocabMasterTests' do
    inherit! :complete
  end

  # use_flipper!  # ← コメントアウト
end

post_install do |installer|
  react_native_post_install(installer)
end